### ISSUE TITLE
Misclicks for browser_click

### ISSUE THREAD

**Issue by tomgutt** [BrowserMCP/mcp#11]
It seems like Cursor AI gets the right idea of which button to click and is also moving the cursor over it but for some reason the actual click is off on the y axis a bit and it clicks the button below the cursor. 
I was thinking it might have something to do with the little debugging notification that appears in the browser.

**Comment by namukang** [comment]
Hey, could you create a screen recording with the issue? Does it happen on all sites or on a particular site? If the latter, it'd be helpful for you to share the URL + prompt so I can reproduce it.

**Comment by gechengyu** [comment]
This problem exists on all websites, including craigslist in the example. The cursor will prompt that there is a problem with the click.

**Comment by namukang** [comment]
Can you share a screen recording and/or the response from the MCP server? (If you click on a MCP call, it will show the response from the MCP server.)

**Comment by jen6** [comment]
Hi @namukang .
I tried in multiple sites but it's all same.
It seems the element ID is changing when snapshot captured.
I use latest version of browser mcp.

- test
 - begin : https://code.visualstudio.com/docs/copilot/chat/mcp-servers
 - instruction : Can you click "Agent Mode" at the sidebar? It's on my browser
 - Error : Error: No tab with given id 818035226. 

https://github.com/user-attachments/assets/c5ce38cc-fed2-480b-8b7d-f086bc6dbaf8

First snapshot
```yaml
- Page URL: https://code.visualstudio.com/docs/copilot/chat/mcp-servers
- Page Title: Use MCP servers in VS Code (Preview)
- Page Snapshot
- document [ref=s3e2]:
...
  - navigation "Topics" [ref=s3e65]:
    - list [ref=s3e66]:
      - listitem [ref=s3e67]:
        - link "Overview" [ref=s3e68]:
          - /url: /docs
      - listitem [ref=s3e69]:
        - button "Setup" [ref=s3e70]
      - listitem [ref=s3e71]:
        - button "Get Started" [ref=s3e72]
      - listitem [ref=s3e73]:
        - button "Configure" [ref=s3e74]
      - listitem [ref=s3e75]:
        - button "Edit code" [ref=s3e76]
      - listitem [ref=s3e77]:
        - button "Build, Debug, Test" [ref=s3e78]
      - listitem [ref=s3e79]:
        - button "Source Control" [ref=s3e80]
      - listitem [ref=s3e81]:
        - button "Terminal" [ref=s3e82]
      - listitem [ref=s3e83]:
        - button "GitHub Copilot" [expanded] [ref=s3e84]
        - list [ref=s3e85]:
          - listitem [ref=s3e86]:
            - link "Overview" [ref=s3e87]:
              - /url: /docs/copilot/overview
          - listitem [ref=s3e88]:
            - link "Setup" [ref=s3e89]:
              - /url: /docs/copilot/setup
          - listitem [ref=s3e90]:
            - link "Quickstart" [ref=s3e91]:
              - /url: /docs/copilot/getting-started
          - listitem [ref=s3e92]:
            - link "Code Completions" [ref=s3e93]:
              - /url: /docs/copilot/ai-powered-suggestions
          - listitem [ref=s3e94]:
            - button "Chat" [expanded] [ref=s3e95]
            - list [ref=s3e96]:
              - listitem [ref=s3e97]:
                - link "Overview" [ref=s3e98]:
                  - /url: /docs/copilot/chat/copilot-chat
              - listitem [ref=s3e99]:
                - link "Tutorial" [ref=s3e100]:
                  - /url: /docs/copilot/chat/getting-started-chat
              - listitem [ref=s3e101]:
                - link "Ask Mode" [ref=s3e102]:
                  - /url: /docs/copilot/chat/chat-ask-mode
              - listitem [ref=s3e103]:
                - link "Edit Mode" [ref=s3e104]:
                  - /url: /docs/copilot/chat/copilot-edits
              - listitem [ref=s3e105]:
                - link "Agent Mode" [ref=s3e106]:
                  - /url: /docs/copilot/chat/chat-agent-mode
              - listitem [ref=s3e107]:
                - 'link "Current Page: MCP Servers" [ref=s3e108]':
                  - /url: /docs/copilot/chat/mcp-servers
                  - text: MCP Servers
...
``````


Second snapshot

```yaml
- Page URL: https://code.visualstudio.com/docs/copilot/chat/mcp-servers
- Page Title: Use MCP servers in VS Code (Preview)
- Page Snapshot

- document [ref=s4e2]:
...
  - navigation "Topics" [ref=s4e65]:
    - list [ref=s4e66]:
      - listitem [ref=s4e67]:
        - link "Overview" [ref=s4e68]:
          - /url: /docs
      - listitem [ref=s4e69]:
        - button "Setup" [ref=s4e70]
      - listitem [ref=s4e71]:
        - button "Get Started" [ref=s4e72]
      - listitem [ref=s4e73]:
        - button "Configure" [ref=s4e74]
      - listitem [ref=s4e75]:
        - button "Edit code" [ref=s4e76]
      - listitem [ref=s4e77]:
        - button "Build, Debug, Test" [ref=s4e78]
      - listitem [ref=s4e79]:
        - button "Source Control" [ref=s4e80]
      - listitem [ref=s4e81]:
        - button "Terminal" [ref=s4e82]
      - listitem [ref=s4e83]:
        - button "GitHub Copilot" [expanded] [ref=s4e84]
        - list [ref=s4e85]:
          - listitem [ref=s4e86]:
            - link "Overview" [ref=s4e87]:
              - /url: /docs/copilot/overview
          - listitem [ref=s4e88]:
            - link "Setup" [ref=s4e89]:
              - /url: /docs/copilot/setup
          - listitem [ref=s4e90]:
            - link "Quickstart" [ref=s4e91]:
              - /url: /docs/copilot/getting-started
          - listitem [ref=s4e92]:
            - link "Code Completions" [ref=s4e93]:
              - /url: /docs/copilot/ai-powered-suggestions
          - listitem [ref=s4e94]:
            - button "Chat" [expanded] [ref=s4e95]
            - list [ref=s4e96]:
              - listitem [ref=s4e97]:
                - link "Overview" [ref=s4e98]:
                  - /url: /docs/copilot/chat/copilot-chat
              - listitem [ref=s4e99]:
                - link "Tutorial" [ref=s4e100]:
                  - /url: /docs/copilot/chat/getting-started-chat
              - listitem [ref=s4e101]:
                - link "Ask Mode" [ref=s4e102]:
                  - /url: /docs/copilot/chat/chat-ask-mode
              - listitem [ref=s4e103]:
                - link "Edit Mode" [ref=s4e104]:
                  - /url: /docs/copilot/chat/copilot-edits
              - listitem [ref=s4e105]:
                - link "Agent Mode" [ref=s4e106]:
                  - /url: /docs/copilot/chat/chat-agent-mode
...
```
